# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Lib\Layout\st_editor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editor(object):
    def setupUi(self, editor):
        editor.setObjectName("editor")
        editor.resize(566, 632)
        self.centralwidget = QtWidgets.QWidget(editor)
        self.centralwidget.setObjectName("centralwidget")
        self.build = QtWidgets.QPushButton(self.centralwidget)
        self.build.setGeometry(QtCore.QRect(9, 9, 170, 30))
        self.build.setMinimumSize(QtCore.QSize(0, 30))
        self.build.setObjectName("build")
        self.import_2 = QtWidgets.QPushButton(self.centralwidget)
        self.import_2.setGeometry(QtCore.QRect(190, 9, 170, 30))
        self.import_2.setMinimumSize(QtCore.QSize(0, 30))
        self.import_2.setObjectName("import_2")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(370, 9, 180, 30))
        self.save_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.save_btn.setObjectName("save_btn")
        self.input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(9, 100, 550, 520))
        self.input.setMinimumSize(QtCore.QSize(0, 0))
        self.input.setPlainText("")
        self.input.setObjectName("input")
        self.add_elements = QtWidgets.QComboBox(self.centralwidget)
        self.add_elements.setGeometry(QtCore.QRect(190, 50, 168, 30))
        self.add_elements.setObjectName("add_elements")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_elements.addItem("")
        self.add_color = QtWidgets.QComboBox(self.centralwidget)
        self.add_color.setGeometry(QtCore.QRect(10, 50, 170, 30))
        self.add_color.setEditable(False)
        self.add_color.setMaxVisibleItems(20)
        self.add_color.setDuplicatesEnabled(False)
        self.add_color.setFrame(True)
        self.add_color.setModelColumn(0)
        self.add_color.setObjectName("add_color")
        self.add_color.addItem("")
        self.add_color.addItem("")
        self.add_color.addItem("")
        self.add_color.addItem("")
        self.add_color.addItem("")
        self.add_color.addItem("")
        self.add_color.addItem("")
        self.add_color.addItem("")
        self.add_color.addItem("")
        self.add_color.addItem("")
        self.add_color.addItem("")
        self.add_resources = QtWidgets.QComboBox(self.centralwidget)
        self.add_resources.setGeometry(QtCore.QRect(370, 50, 180, 30))
        self.add_resources.setObjectName("add_resources")
        self.add_resources.addItem("")
        self.add_resources.addItem("")
        self.add_resources.addItem("")
        editor.setCentralWidget(self.centralwidget)

        self.retranslateUi(editor)
        QtCore.QMetaObject.connectSlotsByName(editor)

    def retranslateUi(self, editor):
        _translate = QtCore.QCoreApplication.translate
        editor.setWindowTitle(_translate("editor", "MainWindow"))
        self.build.setText(_translate("editor", "BUILD"))
        self.build.setShortcut(_translate("editor", "F9"))
        self.import_2.setText(_translate("editor", "IMPORT"))
        self.import_2.setShortcut(_translate("editor", "Ctrl+W"))
        self.save_btn.setText(_translate("editor", "SAVE"))
        self.save_btn.setShortcut(_translate("editor", "Ctrl+S"))
        self.add_elements.setToolTip(_translate("editor", "<html><head/><body><p>Add elements</p></body></html>"))
        self.add_elements.setItemText(0, _translate("editor", "QPushButton"))
        self.add_elements.setItemText(1, _translate("editor", "QWidget"))
        self.add_elements.setItemText(2, _translate("editor", "QMainWidget"))
        self.add_elements.setItemText(3, _translate("editor", "QComboBox"))
        self.add_elements.setItemText(4, _translate("editor", "QToolButton"))
        self.add_elements.setItemText(5, _translate("editor", "QRadioButton"))
        self.add_elements.setItemText(6, _translate("editor", "QCheckBox"))
        self.add_elements.setItemText(7, _translate("editor", "QCommandLinkButton"))
        self.add_elements.setItemText(8, _translate("editor", "QDialogButtonBox"))
        self.add_elements.setItemText(9, _translate("editor", "QListView"))
        self.add_elements.setItemText(10, _translate("editor", "QTreeView"))
        self.add_elements.setItemText(11, _translate("editor", "QTableView"))
        self.add_elements.setItemText(12, _translate("editor", "QColumnView"))
        self.add_elements.setItemText(13, _translate("editor", "QListWidget"))
        self.add_elements.setItemText(14, _translate("editor", "QTreeWidget"))
        self.add_elements.setItemText(15, _translate("editor", "QTableWidget"))
        self.add_color.setToolTip(_translate("editor", "<html><head/><body><p>Add color</p></body></html>"))
        self.add_color.setItemText(0, _translate("editor", "color"))
        self.add_color.setItemText(1, _translate("editor", "background-color"))
        self.add_color.setItemText(2, _translate("editor", "alternate-background-color"))
        self.add_color.setItemText(3, _translate("editor", "border-color"))
        self.add_color.setItemText(4, _translate("editor", "border-top-color"))
        self.add_color.setItemText(5, _translate("editor", "border-right-color"))
        self.add_color.setItemText(6, _translate("editor", "border-bottom-color"))
        self.add_color.setItemText(7, _translate("editor", "border-left-color"))
        self.add_color.setItemText(8, _translate("editor", "gridline-color"))
        self.add_color.setItemText(9, _translate("editor", "selection-color"))
        self.add_color.setItemText(10, _translate("editor", "selection-background-color"))
        self.add_resources.setToolTip(_translate("editor", "<html><head/><body><p>add resources</p></body></html>"))
        self.add_resources.setItemText(0, _translate("editor", "Image"))
        self.add_resources.setItemText(1, _translate("editor", "Icon"))
        self.add_resources.setItemText(2, _translate("editor", "Logo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editor = QtWidgets.QMainWindow()
    ui = Ui_editor()
    ui.setupUi(editor)
    editor.show()
    sys.exit(app.exec_())

