# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Lib\Layout\st_preview.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_preview(object):
    def setupUi(self, preview):
        preview.setObjectName("preview")
        preview.resize(1058, 665)
        self.centralwidget = QtWidgets.QWidget(preview)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(269, 402))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 260, 370))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 180, 240, 190))
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 100, 150))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox_2)
        self.treeWidget.setGeometry(QtCore.QRect(120, 20, 130, 150))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 4, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(230, 215))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 210, 40))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 210, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(10, 140, 210, 40))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 60, 210, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setGeometry(QtCore.QRect(10, 180, 210, 30))
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.groupBox, 0, 1, 2, 1)
        self.build = QtWidgets.QPushButton(self.centralwidget)
        self.build.setObjectName("build")
        self.gridLayout.addWidget(self.build, 0, 3, 1, 1)
        self.import_2 = QtWidgets.QPushButton(self.centralwidget)
        self.import_2.setObjectName("import_2")
        self.gridLayout.addWidget(self.import_2, 0, 4, 1, 1)
        self.export_2 = QtWidgets.QPushButton(self.centralwidget)
        self.export_2.setObjectName("export_2")
        self.gridLayout.addWidget(self.export_2, 0, 5, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setMaximumSize(QtCore.QSize(250, 200))
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 1, 2, 1, 1)
        self.input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.input.setPlainText("")
        self.input.setObjectName("input")
        self.gridLayout.addWidget(self.input, 1, 3, 8, 3)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setMaximumSize(QtCore.QSize(230, 71))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 1, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setMaximumSize(QtCore.QSize(251, 160))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 251, 106))
        self.page.setObjectName("page")
        self.progressBar = QtWidgets.QProgressBar(self.page)
        self.progressBar.setGeometry(QtCore.QRect(10, 0, 230, 20))
        self.progressBar.setMaximumSize(QtCore.QSize(320, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(self.page)
        self.progressBar_2.setGeometry(QtCore.QRect(10, 30, 230, 20))
        self.progressBar_2.setMaximumSize(QtCore.QSize(320, 20))
        self.progressBar_2.setProperty("value", 78)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.checkBox = QtWidgets.QCheckBox(self.page)
        self.checkBox.setGeometry(QtCore.QRect(10, 60, 230, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.radioButton = QtWidgets.QRadioButton(self.page)
        self.radioButton.setGeometry(QtCore.QRect(10, 90, 230, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 251, 106))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout.addWidget(self.toolBox, 2, 2, 2, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(230, 80))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 3, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMaximumSize(QtCore.QSize(270, 150))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 268, 145))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.commandLinkButton.setGeometry(QtCore.QRect(10, 64, 250, 40))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(0, 0, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.timeEdit = QtWidgets.QTimeEdit(self.scrollAreaWidgetContents)
        self.timeEdit.setGeometry(QtCore.QRect(10, 110, 250, 30))
        self.timeEdit.setObjectName("timeEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 4, 0, 4, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMaximumSize(QtCore.QSize(230, 150))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 4, 1, 4, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMaximumSize(QtCore.QSize(250, 30))
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 4, 2, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setMaximumSize(QtCore.QSize(250, 30))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 5, 2, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setMaximumSize(QtCore.QSize(250, 30))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 6, 2, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(250, 30))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 7, 2, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setMaximumSize(QtCore.QSize(270, 30))
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 8, 0, 1, 1)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setMaximumSize(QtCore.QSize(230, 30))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.gridLayout.addWidget(self.horizontalScrollBar, 8, 1, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(250, 30))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 8, 2, 1, 1)
        preview.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(preview)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 21))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        self.menuNew_2 = QtWidgets.QMenu(self.menuNew)
        self.menuNew_2.setObjectName("menuNew_2")
        self.menuMor = QtWidgets.QMenu(self.menubar)
        self.menuMor.setObjectName("menuMor")
        preview.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(preview)
        self.statusbar.setObjectName("statusbar")
        preview.setStatusBar(self.statusbar)
        self.actionCopy = QtWidgets.QAction(preview)
        self.actionCopy.setObjectName("actionCopy")
        self.actionDelete = QtWidgets.QAction(preview)
        self.actionDelete.setObjectName("actionDelete")
        self.actionRemove = QtWidgets.QAction(preview)
        self.actionRemove.setObjectName("actionRemove")
        self.actionCSV = QtWidgets.QAction(preview)
        self.actionCSV.setObjectName("actionCSV")
        self.actionPDF = QtWidgets.QAction(preview)
        self.actionPDF.setObjectName("actionPDF")
        self.actionTXT = QtWidgets.QAction(preview)
        self.actionTXT.setObjectName("actionTXT")
        self.actionWPF = QtWidgets.QAction(preview)
        self.actionWPF.setObjectName("actionWPF")
        self.actionDAT = QtWidgets.QAction(preview)
        self.actionDAT.setObjectName("actionDAT")
        self.actionSFX = QtWidgets.QAction(preview)
        self.actionSFX.setObjectName("actionSFX")
        self.actionAbout = QtWidgets.QAction(preview)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDocs = QtWidgets.QAction(preview)
        self.actionDocs.setObjectName("actionDocs")
        self.actionHelp = QtWidgets.QAction(preview)
        self.actionHelp.setObjectName("actionHelp")
        self.actionCredits = QtWidgets.QAction(preview)
        self.actionCredits.setObjectName("actionCredits")
        self.menuNew_2.addAction(self.actionCSV)
        self.menuNew_2.addAction(self.actionPDF)
        self.menuNew_2.addAction(self.actionTXT)
        self.menuNew_2.addAction(self.actionWPF)
        self.menuNew_2.addAction(self.actionDAT)
        self.menuNew_2.addAction(self.actionSFX)
        self.menuNew.addAction(self.menuNew_2.menuAction())
        self.menuNew.addAction(self.actionCopy)
        self.menuNew.addAction(self.actionDelete)
        self.menuNew.addAction(self.actionRemove)
        self.menuMor.addAction(self.actionAbout)
        self.menuMor.addAction(self.actionDocs)
        self.menuMor.addAction(self.actionHelp)
        self.menuMor.addAction(self.actionCredits)
        self.menubar.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuMor.menuAction())

        self.retranslateUi(preview)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(preview)

    def retranslateUi(self, preview):
        _translate = QtCore.QCoreApplication.translate
        preview.setWindowTitle(_translate("preview", "MainWindow"))
        self.groupBox_2.setTitle(_translate("preview", "GroupBox"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("preview", "WIDGET"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("preview", "TABLE"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("preview", "CONTENT"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("preview", "xxxx"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("preview", "xxxx"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("preview", "xx"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("preview", "xxx"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("preview", "xx"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("preview", "xxx"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("preview", "xx"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("preview", "xxx"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("preview", "xx"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(1)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(2)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(3)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(4)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(5)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(6)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(7)
        item.setText(_translate("preview", "LIST"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget.headerItem().setText(0, _translate("preview", "TREE"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("preview", "New Item"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("preview", "New Item"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("preview", "New Item"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("preview", "New Item"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("preview", "New Item"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("preview", "New Item"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("preview", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("preview", "Tab 2"))
        self.groupBox.setTitle(_translate("preview", "GROUP BOX 1"))
        self.pushButton.setText(_translate("preview", "PushButton"))
        self.lineEdit.setText(_translate("preview", "Line Edit"))
        self.comboBox.setItemText(0, _translate("preview", "Combo box"))
        self.comboBox.setItemText(1, _translate("preview", "Combo box"))
        self.comboBox.setItemText(2, _translate("preview", "Combo box"))
        self.comboBox.setItemText(3, _translate("preview", "Combo box"))
        self.comboBox.setItemText(4, _translate("preview", "Combo box"))
        self.comboBox.setItemText(5, _translate("preview", "Combo box"))
        self.comboBox.setItemText(6, _translate("preview", "Combo box"))
        self.comboBox.setItemText(7, _translate("preview", "Combo box"))
        self.comboBox.setItemText(8, _translate("preview", "Combo box"))
        self.toolButton.setText(_translate("preview", "..."))
        self.build.setText(_translate("preview", "BUILD"))
        self.build.setShortcut(_translate("preview", "F9"))
        self.import_2.setText(_translate("preview", "IMPORT"))
        self.import_2.setShortcut(_translate("preview", "Ctrl+W"))
        self.export_2.setText(_translate("preview", "EXPORT"))
        self.export_2.setShortcut(_translate("preview", "Ctrl+S"))
        self.textEdit.setHtml(_translate("preview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Text Edit</p></body></html>"))
        self.checkBox.setText(_translate("preview", "CheckBox"))
        self.radioButton.setText(_translate("preview", "RadioButton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("preview", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("preview", "Page 2"))
        self.plainTextEdit.setPlainText(_translate("preview", "Plain Text Edit"))
        self.commandLinkButton.setText(_translate("preview", "CommandLinkButton"))
        self.label.setText(_translate("preview", "Scroll Area"))
        self.textBrowser.setHtml(_translate("preview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextBrowser</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menuNew.setTitle(_translate("preview", "File"))
        self.menuNew_2.setTitle(_translate("preview", "New"))
        self.menuMor.setTitle(_translate("preview", "More"))
        self.actionCopy.setText(_translate("preview", "Copy"))
        self.actionDelete.setText(_translate("preview", "Delete"))
        self.actionRemove.setText(_translate("preview", "Remove"))
        self.actionCSV.setText(_translate("preview", "CSV"))
        self.actionPDF.setText(_translate("preview", "PDF"))
        self.actionTXT.setText(_translate("preview", "TXT"))
        self.actionWPF.setText(_translate("preview", "WPF"))
        self.actionDAT.setText(_translate("preview", "DAT"))
        self.actionSFX.setText(_translate("preview", "SFX"))
        self.actionAbout.setText(_translate("preview", "About"))
        self.actionDocs.setText(_translate("preview", "Docs"))
        self.actionHelp.setText(_translate("preview", "Help"))
        self.actionCredits.setText(_translate("preview", "Credits"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    preview = QtWidgets.QMainWindow()
    ui = Ui_preview()
    ui.setupUi(preview)
    preview.show()
    sys.exit(app.exec_())

