# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Lib\Layout\st_preview.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_preview(object):
    def setupUi(self, preview):
        preview.setObjectName("preview")
        preview.resize(774, 601)
        preview.setMinimumSize(QtCore.QSize(774, 601))
        self.centralwidget = QtWidgets.QWidget(preview)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(269, 390))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 260, 370))
        self.groupBox_2.setMinimumSize(QtCore.QSize(260, 370))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 180, 240, 180))
        self.tableWidget.setMinimumSize(QtCore.QSize(240, 180))
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 100, 150))
        self.listWidget.setMinimumSize(QtCore.QSize(100, 150))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox_2)
        self.treeWidget.setGeometry(QtCore.QRect(120, 20, 130, 150))
        self.treeWidget.setMinimumSize(QtCore.QSize(130, 150))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalSlider = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 30, 180, 30))
        self.horizontalSlider.setMinimumSize(QtCore.QSize(84, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalSlider = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider.setGeometry(QtCore.QRect(230, 20, 22, 330))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.tab_2)
        self.verticalScrollBar.setGeometry(QtCore.QRect(200, 20, 16, 330))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.tab_2)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(10, 100, 180, 30))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(230, 215))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 210, 40))
        self.pushButton.setMinimumSize(QtCore.QSize(210, 40))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 210, 30))
        self.lineEdit.setMinimumSize(QtCore.QSize(210, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(10, 140, 210, 40))
        self.buttonBox.setMinimumSize(QtCore.QSize(210, 40))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save|QtWidgets.QDialogButtonBox.SaveAll)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 60, 210, 30))
        self.comboBox.setMinimumSize(QtCore.QSize(210, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setGeometry(QtCore.QRect(10, 180, 210, 30))
        self.toolButton.setMinimumSize(QtCore.QSize(210, 30))
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setMinimumSize(QtCore.QSize(250, 210))
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 2, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(230, 160))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 1, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setMinimumSize(QtCore.QSize(250, 160))
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 250, 115))
        self.page.setObjectName("page")
        self.progressBar = QtWidgets.QProgressBar(self.page)
        self.progressBar.setGeometry(QtCore.QRect(10, 0, 230, 20))
        self.progressBar.setMinimumSize(QtCore.QSize(230, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(self.page)
        self.progressBar_2.setGeometry(QtCore.QRect(10, 30, 230, 20))
        self.progressBar_2.setMinimumSize(QtCore.QSize(230, 20))
        self.progressBar_2.setProperty("value", 78)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.checkBox = QtWidgets.QCheckBox(self.page)
        self.checkBox.setGeometry(QtCore.QRect(10, 56, 230, 30))
        self.checkBox.setMinimumSize(QtCore.QSize(230, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.radioButton = QtWidgets.QRadioButton(self.page)
        self.radioButton.setGeometry(QtCore.QRect(10, 86, 230, 20))
        self.radioButton.setMinimumSize(QtCore.QSize(230, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 250, 115))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout.addWidget(self.toolBox, 1, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(265, 150))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 263, 148))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.commandLinkButton.setGeometry(QtCore.QRect(10, 60, 250, 40))
        self.commandLinkButton.setMinimumSize(QtCore.QSize(250, 40))
        self.commandLinkButton.setCheckable(False)
        self.commandLinkButton.setAutoDefault(False)
        self.commandLinkButton.setDefault(False)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(0, 0, 260, 30))
        self.label.setMinimumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.timeEdit = QtWidgets.QTimeEdit(self.scrollAreaWidgetContents)
        self.timeEdit.setGeometry(QtCore.QRect(10, 110, 250, 30))
        self.timeEdit.setMinimumSize(QtCore.QSize(250, 30))
        self.timeEdit.setObjectName("timeEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 5, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setMinimumSize(QtCore.QSize(230, 71))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 1, 2, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(250, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 2, 2, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(250, 30))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 3, 2, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(230, 70))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 4, 1, 3, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setMinimumSize(QtCore.QSize(250, 20))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 4, 2, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(250, 20))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 5, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMinimumSize(QtCore.QSize(250, 20))
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 6, 2, 1, 1)
        preview.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(preview)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 21))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        self.menuNew_2 = QtWidgets.QMenu(self.menuNew)
        self.menuNew_2.setObjectName("menuNew_2")
        self.menuMor = QtWidgets.QMenu(self.menubar)
        self.menuMor.setObjectName("menuMor")
        self.menu1 = QtWidgets.QMenu(self.menubar)
        self.menu1.setObjectName("menu1")
        self.menu2 = QtWidgets.QMenu(self.menubar)
        self.menu2.setObjectName("menu2")
        self.menu3 = QtWidgets.QMenu(self.menubar)
        self.menu3.setObjectName("menu3")
        preview.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(preview)
        self.statusbar.setObjectName("statusbar")
        preview.setStatusBar(self.statusbar)
        self.actionCopy = QtWidgets.QAction(preview)
        self.actionCopy.setObjectName("actionCopy")
        self.actionDelete = QtWidgets.QAction(preview)
        self.actionDelete.setObjectName("actionDelete")
        self.actionRemove = QtWidgets.QAction(preview)
        self.actionRemove.setObjectName("actionRemove")
        self.actionCSV = QtWidgets.QAction(preview)
        self.actionCSV.setObjectName("actionCSV")
        self.actionPDF = QtWidgets.QAction(preview)
        self.actionPDF.setObjectName("actionPDF")
        self.actionTXT = QtWidgets.QAction(preview)
        self.actionTXT.setObjectName("actionTXT")
        self.actionWPF = QtWidgets.QAction(preview)
        self.actionWPF.setObjectName("actionWPF")
        self.actionDAT = QtWidgets.QAction(preview)
        self.actionDAT.setObjectName("actionDAT")
        self.actionSFX = QtWidgets.QAction(preview)
        self.actionSFX.setObjectName("actionSFX")
        self.actionAbout = QtWidgets.QAction(preview)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDocs = QtWidgets.QAction(preview)
        self.actionDocs.setObjectName("actionDocs")
        self.actionHelp = QtWidgets.QAction(preview)
        self.actionHelp.setObjectName("actionHelp")
        self.actionCredits = QtWidgets.QAction(preview)
        self.actionCredits.setObjectName("actionCredits")
        self.action2 = QtWidgets.QAction(preview)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(preview)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(preview)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(preview)
        self.action5.setObjectName("action5")
        self.action6 = QtWidgets.QAction(preview)
        self.action6.setObjectName("action6")
        self.menuNew_2.addAction(self.actionCSV)
        self.menuNew_2.addAction(self.actionPDF)
        self.menuNew_2.addAction(self.actionTXT)
        self.menuNew_2.addAction(self.actionWPF)
        self.menuNew_2.addAction(self.actionDAT)
        self.menuNew_2.addAction(self.actionSFX)
        self.menuNew.addAction(self.menuNew_2.menuAction())
        self.menuNew.addAction(self.actionCopy)
        self.menuNew.addAction(self.actionDelete)
        self.menuNew.addAction(self.actionRemove)
        self.menuMor.addAction(self.actionAbout)
        self.menuMor.addAction(self.actionDocs)
        self.menuMor.addAction(self.actionHelp)
        self.menuMor.addAction(self.actionCredits)
        self.menu1.addAction(self.action2)
        self.menu1.addAction(self.action3)
        self.menu1.addAction(self.action4)
        self.menu1.addAction(self.action5)
        self.menu1.addAction(self.action6)
        self.menubar.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuMor.menuAction())
        self.menubar.addAction(self.menu1.menuAction())
        self.menubar.addAction(self.menu2.menuAction())
        self.menubar.addAction(self.menu3.menuAction())

        self.retranslateUi(preview)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(preview)

    def retranslateUi(self, preview):
        _translate = QtCore.QCoreApplication.translate
        preview.setWindowTitle(_translate("preview", "MainWindow"))
        self.tabWidget.setToolTip(_translate("preview", "<html><head/><body><p>QTabWidget</p></body></html>"))
        self.groupBox_2.setToolTip(_translate("preview", "<html><head/><body><p>QGroupBox</p></body></html>"))
        self.groupBox_2.setTitle(_translate("preview", "GroupBox"))
        self.tableWidget.setToolTip(_translate("preview", "<html><head/><body><p>QTableWidget</p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("preview", "WIDGET"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("preview", "TABLE"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("preview", "CONTENT"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("preview", "xxxx"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("preview", "xxxx"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("preview", "xx"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("preview", "xxx"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("preview", "xx"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("preview", "xxx"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("preview", "xx"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("preview", "xxx"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("preview", "xx"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.listWidget.setToolTip(_translate("preview", "<html><head/><body><p>QListWidget</p></body></html>"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(1)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(2)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(3)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(4)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(5)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(6)
        item.setText(_translate("preview", "LIST"))
        item = self.listWidget.item(7)
        item.setText(_translate("preview", "LIST"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget.setToolTip(_translate("preview", "<html><head/><body><p>QTreeWidget</p></body></html>"))
        self.treeWidget.headerItem().setText(0, _translate("preview", "TREE"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("preview", "New Item"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("preview", "New Item"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("preview", "New Item"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("preview", "New Item"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("preview", "New Item"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("preview", "New Item"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("preview", "Viewers"))
        self.horizontalSlider.setToolTip(_translate("preview", "<html><head/><body><p>QSlider</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("preview", "Sliders"))
        self.groupBox.setToolTip(_translate("preview", "<html><head/><body><p>QGroupBox</p></body></html>"))
        self.groupBox.setTitle(_translate("preview", "GROUP BOX 1"))
        self.pushButton.setToolTip(_translate("preview", "<html><head/><body><p>QPushButton</p></body></html>"))
        self.pushButton.setText(_translate("preview", "PushButton"))
        self.lineEdit.setToolTip(_translate("preview", "<html><head/><body><p>QLineEdit</p></body></html>"))
        self.lineEdit.setText(_translate("preview", "Line Edit"))
        self.buttonBox.setToolTip(_translate("preview", "<html><head/><body><p>QDialogButtonBox</p></body></html>"))
        self.comboBox.setToolTip(_translate("preview", "<html><head/><body><p>QComboBox</p></body></html>"))
        self.comboBox.setItemText(0, _translate("preview", "Combo box"))
        self.comboBox.setItemText(1, _translate("preview", "Combo box"))
        self.comboBox.setItemText(2, _translate("preview", "Combo box"))
        self.comboBox.setItemText(3, _translate("preview", "Combo box"))
        self.comboBox.setItemText(4, _translate("preview", "Combo box"))
        self.comboBox.setItemText(5, _translate("preview", "Combo box"))
        self.comboBox.setItemText(6, _translate("preview", "Combo box"))
        self.comboBox.setItemText(7, _translate("preview", "Combo box"))
        self.comboBox.setItemText(8, _translate("preview", "Combo box"))
        self.toolButton.setToolTip(_translate("preview", "<html><head/><body><p>QToolButton</p></body></html>"))
        self.toolButton.setText(_translate("preview", "..."))
        self.calendarWidget.setToolTip(_translate("preview", "<html><head/><body><p>QCalendarWidget</p></body></html>"))
        self.textBrowser.setToolTip(_translate("preview", "<html><head/><body><p>QTextBrowser</p></body></html>"))
        self.textBrowser.setHtml(_translate("preview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">QTextBrowser</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 6</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 7</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 8</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 9</p></body></html>"))
        self.toolBox.setToolTip(_translate("preview", "<html><head/><body><p>QToolBox</p></body></html>"))
        self.progressBar.setToolTip(_translate("preview", "<html><head/><body><p>QProgressBar</p></body></html>"))
        self.progressBar_2.setToolTip(_translate("preview", "<html><head/><body><p>QProgressBar</p></body></html>"))
        self.checkBox.setToolTip(_translate("preview", "<html><head/><body><p>QCheckBox</p></body></html>"))
        self.checkBox.setText(_translate("preview", "CheckBox"))
        self.radioButton.setToolTip(_translate("preview", "<html><head/><body><p>QRadioButton</p></body></html>"))
        self.radioButton.setText(_translate("preview", "RadioButton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("preview", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("preview", "Page 2"))
        self.scrollArea.setToolTip(_translate("preview", "<html><head/><body><p>QScrollArea</p></body></html>"))
        self.commandLinkButton.setToolTip(_translate("preview", "<html><head/><body><p>QCommandLinkButton</p></body></html>"))
        self.commandLinkButton.setText(_translate("preview", "CommandLinkButton"))
        self.label.setToolTip(_translate("preview", "<html><head/><body><p>QLabel</p></body></html>"))
        self.label.setText(_translate("preview", "Scroll Area"))
        self.timeEdit.setToolTip(_translate("preview", "<html><head/><body><p>QTimeEdit</p></body></html>"))
        self.textEdit.setToolTip(_translate("preview", "<html><head/><body><p>QTextEdit</p></body></html>"))
        self.textEdit.setHtml(_translate("preview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">QTextEdit</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 6</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 7</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 8</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example 9</p></body></html>"))
        self.lcdNumber.setToolTip(_translate("preview", "<html><head/><body><p>QLCDNumber</p></body></html>"))
        self.dateTimeEdit.setToolTip(_translate("preview", "<html><head/><body><p>QDateTimeEdit</p></body></html>"))
        self.plainTextEdit.setToolTip(_translate("preview", "<html><head/><body><p>QPlainTextEdit</p></body></html>"))
        self.plainTextEdit.setPlainText(_translate("preview", "Plain Text Edit\n"
"Example 1\n"
"Example 2\n"
"Example 3\n"
"Example 4\n"
"Example 5\n"
"Example 6\n"
"Example 7\n"
"Example 8\n"
"Example 9"))
        self.dateEdit.setToolTip(_translate("preview", "<html><head/><body><p>QDateEdit</p></body></html>"))
        self.doubleSpinBox.setToolTip(_translate("preview", "<html><head/><body><p>QDoubleSpinBox</p></body></html>"))
        self.spinBox.setToolTip(_translate("preview", "<html><head/><body><p>QSpinBox</p></body></html>"))
        self.menuNew.setTitle(_translate("preview", "File"))
        self.menuNew_2.setTitle(_translate("preview", "New"))
        self.menuMor.setTitle(_translate("preview", "More"))
        self.menu1.setTitle(_translate("preview", "1"))
        self.menu2.setTitle(_translate("preview", "2"))
        self.menu3.setTitle(_translate("preview", "3"))
        self.actionCopy.setText(_translate("preview", "Copy"))
        self.actionDelete.setText(_translate("preview", "Delete"))
        self.actionRemove.setText(_translate("preview", "Remove"))
        self.actionCSV.setText(_translate("preview", "CSV"))
        self.actionPDF.setText(_translate("preview", "PDF"))
        self.actionTXT.setText(_translate("preview", "TXT"))
        self.actionWPF.setText(_translate("preview", "WPF"))
        self.actionDAT.setText(_translate("preview", "DAT"))
        self.actionSFX.setText(_translate("preview", "SFX"))
        self.actionAbout.setText(_translate("preview", "About"))
        self.actionDocs.setText(_translate("preview", "Docs"))
        self.actionHelp.setText(_translate("preview", "Help"))
        self.actionCredits.setText(_translate("preview", "Credits"))
        self.action2.setText(_translate("preview", "2"))
        self.action3.setText(_translate("preview", "3"))
        self.action4.setText(_translate("preview", "4"))
        self.action5.setText(_translate("preview", "5"))
        self.action6.setText(_translate("preview", "6"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    preview = QtWidgets.QMainWindow()
    ui = Ui_preview()
    ui.setupUi(preview)
    preview.show()
    sys.exit(app.exec_())

